# Generated by Django 2.1.7 on 2019-03-07 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aircraft', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msn', models.CharField(max_length=500, unique=True)),
                ('fuel_quantity_left_wing', models.IntegerField()),
                ('fuel_quantity_right_wing', models.IntegerField()),
                ('maximum_altitude', models.IntegerField()),
                ('flight_aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aircraft.AirCraft')),
            ],
        ),
    ]
