# Generated by Django 2.1.7 on 2019-03-07 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
        ('flight_route', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey_date', models.DateField()),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.Flight')),
            ],
        ),
        migrations.RemoveField(
            model_name='flightroute',
            name='flight',
        ),
        migrations.AddField(
            model_name='flightroute',
            name='flight_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journeyinfo',
            name='flight_route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_route.FlightRoute'),
        ),
    ]
